server:
  port: 9002

spring:
  application:
    name: Management-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

keycloak:
  realm: master
  auth-server-url: http://localhost:8181
  ssl-required: external
  resource: spring-boot-microservice-keycloak
  bearer-only: true
  public-client: true

resilience4j:
  circuitbreaker:
    instances:
      management:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50

management:
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
