spring:
  name: Report-service
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootreport
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queues:
      adv-queue:
        name: queue-advertisement
        exchange: adv-exchange
        routing-key: adv-routing
  main:
    allow-bean-definition-overriding: true

server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
